
   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app.js-deployment
  labels:
    app: app.js
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app.js
  template:
    metadata:
      labels:
        app: app.js
    spec:
      containers:
      - name: appserver
        image: upe123/app.js:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: app.js-service
spec:
  selector:
    app: app.js
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
